#!/bin/bash

# 关闭代理
unset http_proxy
unset https_proxy
unset all_proxy

nowPath=`pwd`

# 初始化conda环境，可直接从~/.bashrc或~/.zshrc中复制  need to edit
__conda_setup="$('/opt/anaconda/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/opt/anaconda/etc/profile.d/conda.sh" ]; then
        . "/opt/anaconda/etc/profile.d/conda.sh"
    else
        export PATH="/opt/anaconda/bin:$PATH"
    fi
fi
unset __conda_setup

# 进入本项目的目录并登录
cd ~/p-dot-nju-login  # need to edit
conda activate NJUlogin  # need to edit
python main.py -i -l pwdLogin -u xxxxxxxxx -w xxxxxxxxx  # need to edit
conda deactivate
cd $nowPath
$*
excode=$?

cd ~/p-dot-nju-login  # need to edit
conda activate NJUlogin  # need to edit
python main.py -o
conda deactivate
cd $nowPath
exit $excode
